name: Create Git Tag

description: Create Git Tag

inputs:
  tag:
    required: true
    description: tag

runs:
  using: "composite"
  steps:
    - name: Git checkout
      uses: actions/checkout@v3
      with:
        ref: "main"

    - name: Set Vars
      run: |
        echo "MESSAGE=$(echo '${{github.event.head_commit.message}}'|head -n 1)" >> $GITHUB_ENV
        echo "CURRENT_DATE=$(date +'%Y-%m-%d %H:%M')" >> $GITHUB_ENV
        echo "BRANCH=rc/${{ inputs.tag }}" >> $GITHUB_ENV

    - name: Create GH Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ inputs.tag }}
        release_name: Release ${{ inputs.tag }}
        commitish: ${{env.BRANCH}}
        body: |
          Changes in this Release
          - Release from: ${{env.BRANCH}}
          - Release date: ${{env.CURRENT_DATE}}
          - Commit: ${{github.sha}}
          - Commit Message: ${{env.MESSAGE}}
        draft: false
        prerelease: true

    - name: Send Message to Slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{job.status}}
        username: "CREATE_TAG|${{github.event.repository.name}}|${{ inputs.tag }}"
        author_name: ${{github.workflow}}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest
      if: always()
